from playwright.sync_api import sync_playwright

URL = "http://localhost:8123/dist/react/index-react.html"

with sync_playwright() as p:
    browser = p.chromium.launch(headless=True)
    page = browser.new_page()
    page.on("console", lambda m: print("CONSOLE:", m.type, m.text))
    page.on("pageerror", lambda e: print("PAGEERROR:", e))
    page.on("requestfailed", lambda r: print("REQFAILED:", r.url, r.failure))
    page.goto(URL)
    page.wait_for_load_state("networkidle")
    editor = page.locator("#q-editor")
    editor.click()
    editor.fill("明日は遠足です。")
    status = page.locator(".q-furigana-status")
    page.wait_for_function("document.querySelector('.q-furigana-status').textContent === ''", timeout=15000)
    print("kuromoji ready, status text:", repr(status.inner_text()))
    editor.click()
    editor.evaluate("el => { el.setSelectionRange(0, el.value.length); el.dispatchEvent(new Event('select', {bubbles:true})); }")
    sel = editor.evaluate("el => [el.selectionStart, el.selectionEnd]")
    print("selection after select-all:", sel)
    page.wait_for_timeout(150)
    ruby_btn = page.locator("button", has_text="ふりがな")
    print("ruby button disabled?", ruby_btn.is_disabled())
    ruby_btn.click()
    page.wait_for_timeout(500)
    print("editor value after ruby apply:", editor.input_value())

    editor.fill("")
    editor.fill("明日は遠足です。")
    editor.click()
    editor.evaluate("el => { el.setSelectionRange(0, el.value.length); el.dispatchEvent(new Event('select', {bubbles:true})); }")
    page.wait_for_timeout(150)
    write_btn = page.locator("button", has_text="漢字を問題に")
    write_btn.click()
    page.wait_for_timeout(300)
    print("editor value after write-box apply:", editor.input_value())

    browser.close()
